from typing import Awaitable, Callable, Protocol

from ari.domain.whatsapp.entities import InboundWhatsApp

OnMessage = Callable[[InboundWhatsApp], Awaitable[None]]


class WhatsAppPort(Protocol):
    async def start(self, on_message: OnMessage) -> None: ...
    async def send(self, wa_chat_id: str, text: str) -> None: ...
    async def pair_phone(self, number: str) -> str: ...
    def connection_state(self) -> str: ...
