from typing import Protocol

from ari.domain.agent.message import Message
from ari.domain.memory.entities import Fact, Recall, Summary


class MemoryPort(Protocol):
    async def recent_messages(self, user_id: str, limit: int) -> list[Message]: ...
    async def append_message(self, message: Message) -> None: ...
    async def store_recall(self, user_id: str, content: str,
                           embedding: list[float], metadata: dict) -> None: ...
    async def retrieve_recalls(self, user_id: str, query_embedding: list[float],
                               k: int) -> list[Recall]: ...
    async def get_facts(self, user_id: str) -> list[Fact]: ...
    async def upsert_fact(self, user_id: str, key: str, value: str) -> None: ...
    async def delete_fact(self, user_id: str, key: str) -> bool: ...
    async def get_summary(self, user_id: str) -> Summary | None: ...
    async def upsert_summary(self, user_id: str, content: str) -> None: ...
