from typing import Protocol

from ari.domain.grants.entities import Grant


class GrantPort(Protocol):
    async def upsert(self, grantor_id: str, grantee_id: str, capability: str, level: str) -> None: ...
    async def get(self, grantor_id: str, grantee_id: str, capability: str) -> Grant | None: ...
    async def given_by(self, grantor_id: str) -> list[Grant]: ...
    async def received_by(self, grantee_id: str) -> list[Grant]: ...
    async def revoke(self, grantor_id: str, grantee_id: str, capability: str) -> bool: ...
    async def delete_for_user(self, user_id: str) -> int: ...
