from typing import Protocol

from ari.domain.email.entities import EmailAccount, EmailAccountSummary


class EmailAccountsPort(Protocol):
    async def add(self, account: EmailAccount) -> None: ...
    async def list_for_user(self, user_id: str) -> list[EmailAccount]: ...
    async def summaries_for(self, user_id: str) -> list[EmailAccountSummary]: ...
    async def remove(self, user_id: str, label: str) -> bool: ...
    async def delete_for_user(self, user_id: str) -> int: ...
