from typing import Protocol

from ari.domain.access.entities import AccessRecord


class AccessPort(Protocol):
    async def get(self, user_id: str) -> AccessRecord | None: ...
    async def find_by_code(self, code: str) -> AccessRecord | None: ...
    async def create_pending(self, user_id: str, username: str | None, code: str) -> None: ...
    async def set_status(self, user_id: str, status: str) -> None: ...
    async def delete(self, user_id: str) -> None: ...
    async def list_all(self) -> list[AccessRecord]: ...
