import json
import logging
from datetime import timedelta

from ari.application.access.gate import format_code
from ari.domain.schedule.quiet_hours import is_quiet

log = logging.getLogger("ari.notices")

_QUEUE = "notices.queue"
_CLI_DOWN = "notices.cli_down"


class SystemNotices:
    """Owner-only operational notices, generated by code (no Claude), so they
    work even when Claude is down. Queued during quiet hours."""

    def __init__(self, kv, access, owners: set[str], send, tz, quiet, clock,
                 stale_after: timedelta = timedelta(hours=12)):
        self._kv, self._access, self._owners = kv, access, sorted(owners)
        self._send, self._tz, self._quiet = send, tz, quiet
        self._clock, self._stale_after = clock, stale_after

    def _is_quiet(self) -> bool:
        return is_quiet(self._clock().astimezone(self._tz), self._quiet)

    async def _to_owners(self, text: str) -> None:
        for owner in self._owners:
            await self._send(owner, text)

    async def emit(self, text: str) -> None:
        if self._is_quiet():
            queue = json.loads(await self._kv.kv_get(_QUEUE) or "[]")
            await self._kv.kv_set(_QUEUE, json.dumps([*queue, text], ensure_ascii=False))
        else:
            await self._to_owners(text)

    async def tick(self) -> None:
        await self._flush()
        await self._check_access()

    async def _flush(self) -> None:
        if self._is_quiet():
            return
        queue = json.loads(await self._kv.kv_get(_QUEUE) or "[]")
        if queue:
            await self._kv.kv_delete(_QUEUE)
            await self._to_owners("📬 Avisos mientras estaba en silencio:\n"
                                  + "\n".join(f"• {q}" for q in queue))

    async def _check_access(self) -> None:
        now = self._clock()
        for rec, since in await self._access.pending_since():
            key = f"notices.access:{rec.code}"
            if now - since < self._stale_after or await self._kv.kv_get(key):
                continue
            await self._kv.kv_set(key, "1")
            who = f"@{rec.username} (id {rec.user_id})" if rec.username else f"id {rec.user_id}"
            # Send stale access requests immediately, bypassing quiet hours queue
            await self._to_owners(f"🔔 {who} sigue esperando acceso. "
                                  f"Aprueba con: /aprobar {format_code(rec.code)}")

    async def task_paused(self, item, reason: str) -> None:
        await self.emit(f"⏸️ Pausé la tarea #{item.id} ({item.text[:60]}) "
                        f"porque falló 3 veces: {reason}")

    async def cli_failed(self, reason: str) -> None:
        if await self._kv.kv_get(_CLI_DOWN):
            return
        await self._kv.kv_set(_CLI_DOWN, "1")
        await self.emit(f"⚠️ Estoy teniendo problemas con Claude: «{reason[:200]}». "
                        "Revisa el token o la conexión.")

    async def cli_recovered(self) -> None:
        if not await self._kv.kv_get(_CLI_DOWN):
            return
        await self._kv.kv_delete(_CLI_DOWN)
        await self.emit("✅ Claude volvió a responder.")
